# Cargo 配置文件
# 用于控制编译行为

# Linux 特定配置：强制使用 WebKitGTK 4.1
[target.x86_64-unknown-linux-gnu]
rustflags = [
    # 链接到 webkit2gtk-4.1 而不是 webkit2gtk-4.0
    "-C", "link-arg=-lwebkit2gtk-4.1"
]

# 环境变量：指导 pkg-config 优先使用 webkit2gtk-4.1
[env]
# 优先查找 webkit2gtk-4.1 的 pkg-config 文件
PKG_CONFIG_PATH = "/usr/lib/x86_64-linux-gnu/pkgconfig"

